/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TelaPrincipal;

import ClasseFile.TipoFile;
import ManipulacaoFile.Funcoes;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.security.Principal;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.jpl7.fli.qid_t;

/**
 *
 * @author higor
 */
public final class TelaQuestoes extends javax.swing.JFrame {

    int contadorArquivo = 0;
    String nomeAux = "";
    String quest = "";
    int pontuacao = 0;
    int contaClique = 0;

    /**
     * Creates new form TelaClima
     *
     * @throws java.io.IOException
     */
    public TelaQuestoes(String nome, String questao) throws IOException {
        initComponents();
        Color minhaCor = new Color(173, 216, 230);
        getContentPane().setBackground(minhaCor);
        nomeAux = nome;
        quest = questao;
        mostrar(nomeAux);
        String sl=nome.replace("src/Questoes/","");
        String sl2= sl.replace(".txt", "");
        //jTextFieldTema.setText(nome.replace("src/Questoes/", "").toUpperCase());
        jTextFieldTema.setText(sl2.toUpperCase());
         
        
    }

    private TelaQuestoes() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void mostrar(String nome) throws IOException {
        TipoFile tipo = new TipoFile();
        Funcoes f = new Funcoes();
        //String a = "Transporte.txt";
        ArrayList<String> aux = new ArrayList<>();
        aux = f.manipulaArquivo(nome);
        if (contadorArquivo < aux.size()) {
            jTextPaneTexto.setText(String.valueOf(aux.get(contadorArquivo++)));

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldResposta = new javax.swing.JTextField();
        jButtonEnviar = new javax.swing.JButton();
        jTextFieldPontuacao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonVolta = new javax.swing.JButton();
        jTextFieldTema = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneTexto = new javax.swing.JTextPane();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Digite a alternativa da questão: ");

        jTextFieldResposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRespostaActionPerformed(evt);
            }
        });

        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });

        jTextFieldPontuacao.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PONTUAÇÃO");

        jButtonVolta.setText("Voltar");
        jButtonVolta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltaActionPerformed(evt);
            }
        });

        jTextFieldTema.setEditable(false);
        jTextFieldTema.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTema.setEnabled(false);

        jTextPaneTexto.setEditable(false);
        jTextPaneTexto.setFont(new java.awt.Font("Noto Sans", 1, 12)); // NOI18N
        jTextPaneTexto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(jTextPaneTexto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButtonVolta)
                        .addGap(0, 900, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButtonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldTema, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldPontuacao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPontuacao, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTema, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldResposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonVolta)
                .addGap(72, 72, 72))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonEnviar, jLabel1, jTextFieldResposta});

        setSize(new java.awt.Dimension(991, 434));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldRespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRespostaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRespostaActionPerformed

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed
        boolean clicou = true;
        try {
            Funcoes f = new Funcoes();
            if (!jTextFieldResposta.getText().equals("")) {
                contaClique += 1;
                if (contaClique < 6) {
                    if (clicou == true) {

                        if (f.AvaliaQuestao(String.valueOf(quest), String.valueOf(jTextFieldResposta.getText()), contaClique) == true) {
                            pontuacao += 10;
                            jTextFieldPontuacao.setBackground(Color.GREEN);
                            jTextFieldPontuacao.setText(String.valueOf(pontuacao));
                            jTextFieldResposta.setText("");
                        } else {
                            jTextFieldPontuacao.setBackground(Color.RED);
                        }
                        jTextFieldResposta.setText("");

                    }
                    clicou = false;
                    mostrar(nomeAux);

                }

                if (contaClique == 5) {
                    JOptionPane.showMessageDialog(null, "Sua pontuação foi: " + pontuacao + "!");
                    new TelaPrincipal().setVisible(true);
                    dispose();
                }

            } else {
                JOptionPane.showMessageDialog(null, "Digite a alternativa!");

            }
        } catch (IOException ex) {
            Logger.getLogger(TelaQuestoes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jButtonVoltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltaActionPerformed
        // TODO add your handling code here:
        String messagem = "Você deseja realmente voltar? ";
        String title = "Voltar";
        int msg = JOptionPane.showConfirmDialog(null, messagem, title, JOptionPane.YES_NO_OPTION);
        if (msg == JOptionPane.YES_OPTION) {
            new TelaPrincipal().setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_jButtonVoltaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaQuestoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaQuestoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JButton jButtonVolta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextFieldPontuacao;
    private javax.swing.JTextField jTextFieldResposta;
    private javax.swing.JTextField jTextFieldTema;
    private javax.swing.JTextPane jTextPaneTexto;
    // End of variables declaration//GEN-END:variables
}
